language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "ff025b51dc5156fe9da0b707c5a5ca745245e27e"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true

services: mongodb
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar